require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "bin/*"
    - "exe/*"

# Style
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false # We use YARD for documentation

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/HashSyntax:
  EnforcedStyle: ruby19

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'  # Allow long comments

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

# Naming
Naming/MethodParameterName:
  MinNameLength: 2

# Performance
Performance/StringReplacement:
  Enabled: true
