name: Ruby

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run RuboCop
      run: bundle exec rubocop
    
    - name: Run tests
      run: bundle exec rake spec
      env:
        COVERAGE: true
    
    - name: Upload coverage to Codecov
      if: matrix.ruby-version == '3.3'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/coverage.xml
        fail_ci_if_error: false

  gem-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Build gem
      run: gem build wittyflow.gemspec
    
    - name: Upload gem artifact
      uses: actions/upload-artifact@v3
      with:
        name: wittyflow-gem
        path: '*.gem'

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Run bundle audit
      run: |
        gem install bundler-audit
        bundle audit --update
    
    - name: Run Brakeman (if applicable)
      run: |
        if gem list -i brakeman; then
          bundle exec brakeman --no-pager
        else
          echo "Brakeman not applicable for gem projects"
        fi
      continue-on-error: true